name: cli_script
version: 1.0.11
description: Write scripts that call subprocesses with the ease of shell scripting and the power of Dart.
repository: https://github.com/open-runtime/dart_cli_script
environment:
  sdk: ^3.9.0


dependencies:
  async: ^2.13.0
  charcode: ^1.4.0
  collection: ^1.19.1
  glob: ^2.1.3
  meta: ^1.16.0
  path: ^1.9.1
  source_span: ^1.10.1
  stack_trace: ^1.12.1
  string_scanner: ^1.4.1
  tuple: ^2.0.2
dev_dependencies:
  runtime_ci_tooling:
    git:
      url: git@github.com:open-runtime/runtime_ci_tooling.git
      tag_pattern: "v{{version}}"
    version: ^0.14.1
  test: ^1.25.15
  test_descriptor: ^2.0.2
